language:
    go

before_install:
    - gvm implode # Remove gvm because it does not have go1.1
    - export GOROOT=
    - sudo add-apt-repository --yes ppa:czchen/travis-ci
    - sudo apt-get update -qq
    - sudo apt-get install -qq golang-stable # Install go1.1

install:
    echo "install"

before_script:
    echo "before_script"

script:
    /usr/bin/go test ./...
